services:
  redis_1:
    image: redis:latest
    hostname: redis_1
    command: redis-server /conf/7000/redis.conf
    ports:
      - "7000:7000"
    volumes:
      - ./conf:/conf
      - ./data/7000:/data
  redis_2:
    image: redis:latest
    hostname: redis_2
    command: redis-server /conf/7001/redis.conf
    ports:
      - "7001:7001"
    volumes:
      - ./conf:/conf
      - ./data/7001:/data
  redis_3:
    image: redis:latest
    hostname: redis_3
    command: redis-server /conf/7002/redis.conf
    ports:
      - "7002:7002"
    volumes:
      - ./conf:/conf
      - ./data/7002:/data
  redis_4:
    image: redis:latest
    hostname: redis_4
    command: redis-server /conf/7003/redis.conf
    ports:
      - "7003:7003"
    volumes:
      - ./conf:/conf
      - ./data/7003:/data
  redis_5:
    image: redis:latest
    hostname: redis_5
    command: redis-server /conf/7004/redis.conf
    ports:
      - "7004:7004"
    volumes:
      - ./conf:/conf
      - ./data/7004:/data
  redis_6:
    image: redis:latest
    hostname: redis_6
    command: redis-server /conf/7005/redis.conf
    ports:
      - "7005:7005"
    volumes:
      - ./conf:/conf
      - ./data/7005:/data
  redis_cluster:
    image: redis:latest
    hostname: redis_cluster
    command: redis-cli --cluster create redis_1:7000 redis_2:7001 redis_3:7002 redis_4:7003 redis_5:7004 redis_6:7005 --cluster-replicas 1 --cluster-yes
    volumes:
      - ./conf:/conf
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
